### ISSUE TITLE
ios icon not being generated and no error

### ISSUE THREAD

**Issue by gedw99** [franzsilva/flutter_launcher_icons#8]
android works.
but not ios.

anyone else getting this ?

from project root calling:
flutter pub pub run flutter_launcher_icons:main

---

pubspec.yaml
````

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.0.1"

flutter_icons:
  image_path: "icon.png" 
  android: true
  ios: true

````

---

**Comment by MarkOSullivan94** [comment]
How are you checking this? Are you checking the launcher icon within the emulated device or within the iOS project assets directory?

**Comment by gedw99** [comment]
I am checking the IOS project assets dir.

when i make IOS : false, then the android ones to get generated.

**Comment by MarkOSullivan94** [comment]
Will go back and try and replicate this before making a pull request for this feature: https://github.com/franzsilva/flutter_launcher_icons/issues/6

**Comment by MarkOSullivan94** [comment]
@gedw99 should be fixed when this is merged in: https://github.com/franzsilva/flutter_launcher_icons/pull/9

**Comment by franzsilva** [comment]
@gedw99 , ive merged the pull request and updated the package to 0.2.0, give it a try and let us know

**Comment by MarkOSullivan94** [comment]
@franzsilva might be worth closing this for now as this should be fixed with the latest update.

**Comment by Zulqurnain** [comment]
0.2.0 is still not generating launcher icon for iOS , i'm stuck can anyone help me out

**Comment by Zulqurnain** [comment]
Oh i solved my issue , i thought visual studio will run those commands for me automatically , but that is not the case , you have to manually run those commands by going to your project folder from CMD/Terminal

**Comment by MarkOSullivan94** [comment]
Seems to be fixed. Closing this issue.
